#!/usr/bin/env bun
/**
 * cerebro-codegen — emits the flag keys and their declared types so `get()`
 * narrows per key.
 *
 *   cerebro-codegen --app checkout --url http://localhost:3011 \
 *                   --email you@example.com --password ... \
 *                   --out src/cerebro-flags.d.ts
 *
 * Flags belong to an application, so the generated map covers one application —
 * the same one your SDK key resolves to. `--app` may be omitted when only one
 * application exists.
 *
 * Credentials can come from CEREBRO_URL, CEREBRO_EMAIL and CEREBRO_PASSWORD
 * instead. Reads the management API, so it needs a login — not an SDK key.
 */

interface FlagRecord {
  key: string;
  name: string;
  description: string;
  type: "boolean" | "string" | "number" | "json";
  archivedAt: string | null;
}

const TS_TYPE: Record<FlagRecord["type"], string> = {
  boolean: "boolean",
  string: "string",
  number: "number",
  json: "unknown",
};

function arg(name: string): string | undefined {
  const index = Bun.argv.indexOf(`--${name}`);
  if (index !== -1) return Bun.argv[index + 1];
  const inline = Bun.argv.find((value) => value.startsWith(`--${name}=`));
  return inline?.slice(name.length + 3);
}

function required(name: string, envName: string): string {
  const value = arg(name) ?? Bun.env[envName];
  if (!value) {
    console.error(`Missing --${name} (or ${envName})`);
    process.exit(1);
  }
  return value;
}

const baseUrl = (arg("url") ?? Bun.env.CEREBRO_URL ?? "http://localhost:3011").replace(/\/$/, "");
const email = required("email", "CEREBRO_EMAIL");
const password = required("password", "CEREBRO_PASSWORD");
const out = arg("out") ?? "cerebro-flags.d.ts";

const login = await fetch(`${baseUrl}/v1/auth/login`, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ email, password }),
});

if (!login.ok) {
  console.error(`Could not sign in to ${baseUrl}: ${login.status}`);
  process.exit(1);
}

const cookie = login.headers.get("set-cookie")?.split(";")[0];
if (!cookie) {
  console.error("The server did not return a session cookie");
  process.exit(1);
}

interface ApplicationRecord {
  key: string;
}

const appsResponse = await fetch(`${baseUrl}/v1/mgmt/applications`, {
  headers: { Cookie: cookie },
});
if (!appsResponse.ok) {
  console.error(`Could not read applications: ${appsResponse.status}`);
  process.exit(1);
}
const { items: applications } = (await appsResponse.json()) as { items: ApplicationRecord[] };

const requestedApp = arg("app") ?? Bun.env.CEREBRO_APP;
let applicationKey: string;

if (requestedApp) {
  if (!applications.some((a) => a.key === requestedApp)) {
    const available = applications.map((a) => a.key).join(", ") || "none";
    console.error(`No application '${requestedApp}'. Available: ${available}`);
    process.exit(1);
  }
  applicationKey = requestedApp;
} else if (applications.length === 1 && applications[0]) {
  applicationKey = applications[0].key;
} else {
  console.error(
    applications.length === 0
      ? "There are no applications yet — an admin creates one before flags can exist."
      : `Several applications exist. Pass --app <key>: ${applications.map((a) => a.key).join(", ")}`,
  );
  process.exit(1);
}

const flags: FlagRecord[] = [];
let cursor: string | null = null;

do {
  const query = new URLSearchParams({ limit: "200" });
  if (cursor) query.set("cursor", cursor);

  const response = await fetch(
    `${baseUrl}/v1/mgmt/applications/${applicationKey}/flags?${query.toString()}`,
    { headers: { Cookie: cookie } },
  );
  if (!response.ok) {
    console.error(`Could not read flags: ${response.status}`);
    process.exit(1);
  }

  const page = (await response.json()) as { items: FlagRecord[]; nextCursor: string | null };
  flags.push(...page.items);
  cursor = page.nextCursor;
} while (cursor);

const active = flags
  .filter((flag) => flag.archivedAt === null)
  .sort((a, b) => a.key.localeCompare(b.key));

const entries = active
  .map((flag) => {
    const comment = flag.description.trim() || flag.name;
    return `    /** ${comment.replace(/\*\//g, "*\\/")} */\n    ${JSON.stringify(flag.key)}: ${TS_TYPE[flag.type]};`;
  })
  .join("\n");

const contents = `// Generated by cerebro-codegen. Do not edit — re-run the command instead.
// Source: ${baseUrl}
// Application: ${applicationKey} — ${active.length} flag${active.length === 1 ? "" : "s"}
//
// One application's flags. An SDK key resolves to one application too, so this
// map is exactly what that key will receive.

import "@cerebro/sdk";

declare module "@cerebro/sdk" {
  interface FlagMap {
${entries}
  }
}
`;

await Bun.write(out, contents);
console.log(`wrote ${out} — ${active.length} flags for '${applicationKey}'`);
