import type { FlagTypeName } from "../core/manifest";

/**
 * Turning flag records into a file. Kept apart from the CLI so it can be tested
 * without a server, a login, or a filesystem.
 */

/** One row of `GET /v1/mgmt/applications/{app}/flags`. */
export interface FlagRecord {
  key: string;
  name: string;
  description: string;
  type: FlagTypeName;
  defaultValue: unknown;
  isClientSafe?: boolean;
  archivedAt: string | null;
}

export interface EmitMeta {
  application: string;
  source: string;
  generatedAt: string;
}

const TS_TYPE: Record<FlagTypeName, string> = {
  boolean: "boolean",
  string: "string",
  number: "number",
  // The server stores arbitrary JSON, so there is nothing narrower to say.
  json: "unknown",
};

/** Archived flags are gone from every payload, so they are gone from here. */
export function activeFlags(records: readonly FlagRecord[]): FlagRecord[] {
  return records
    .filter((flag) => flag.archivedAt === null)
    .sort((a, b) => a.key.localeCompare(b.key));
}

function comment(flag: FlagRecord): string {
  const text = flag.description.trim() || flag.name;
  return text.replace(/\*\//g, "*\\/");
}

function header(meta: EmitMeta, count: number): string {
  return `// Generated by cerebro-codegen. Do not edit — re-run the command instead.
// Source: ${meta.source}
// Application: ${meta.application} — ${count} flag${count === 1 ? "" : "s"}`;
}

/**
 * The default output: one module that is both the runtime manifest and the
 * types. Deriving the types from the value means the two cannot drift, and
 * importing the manifest — which you have to do anyway to pass it to the
 * client — is what applies the augmentation.
 */
export function renderManifest(records: readonly FlagRecord[], meta: EmitMeta): string {
  const active = activeFlags(records);

  const entries = active
    .map((flag) => {
      const fields = [`type: ${JSON.stringify(flag.type)}`, `default: ${literal(flag.defaultValue)}`];
      if (flag.isClientSafe !== undefined) fields.push(`clientSafe: ${String(flag.isClientSafe)}`);
      return `    /** ${comment(flag)} */\n    ${JSON.stringify(flag.key)}: { ${fields.join(", ")} },`;
    })
    .join("\n");

  return `${header(meta, active.length)}
//
// Two jobs in one file: the manifest you hand to createClient or
// CerebroProvider, and the flag types. Import it once and both apply.

import type { FlagManifest, InferFlagMap } from "@cerebro/client";

export const manifest = {
  version: 1,
  application: ${JSON.stringify(meta.application)},
  generatedAt: ${JSON.stringify(meta.generatedAt)},
  source: ${JSON.stringify(meta.source)},
  flags: {
${entries}
  },
} as const satisfies FlagManifest;

declare module "@cerebro/client" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface FlagMap extends InferFlagMap<typeof manifest> {}
}
`;
}

/**
 * Types only, for a JavaScript project that has no use for the runtime half.
 * Validation and offline defaults need the manifest, so this gives up both.
 */
export function renderDeclaration(records: readonly FlagRecord[], meta: EmitMeta): string {
  const active = activeFlags(records);

  const entries = active
    .map((flag) => `    /** ${comment(flag)} */\n    ${JSON.stringify(flag.key)}: ${TS_TYPE[flag.type]};`)
    .join("\n");

  return `${header(meta, active.length)}
//
// Types only. Generate the .ts form instead if you want payload validation and
// offline defaults — those need the manifest at runtime.

import "@cerebro/client";

declare module "@cerebro/client" {
  interface FlagMap {
${entries}
  }
}
`;
}

/** A JSON value as TypeScript source. The two literal syntaxes agree here. */
function literal(value: unknown): string {
  return value === undefined ? "null" : JSON.stringify(value);
}
